# Generated by Django 6.0.8 on 2026-08-25 08:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('body', wagtail.fields.StreamField([('service_category', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 100}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. '€25' or 'from €9,50'", 'max_length': 50}), 3: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. '45 mins' or '1 hr 15 mins'", 'max_length': 30, 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': "Optional badge, e.g. 'Off peak' or 'Save up to 5%'", 'max_length': 50, 'required': False}), 5: ('wagtail.blocks.StructBlock', [[('name', 0), ('description', 1), ('price', 2), ('duration', 3), ('badge', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.StructBlock', [[('category_name', 0), ('services', 6)]], {})})),
                ('booking_url', models.URLField(blank=True, help_text='Link to your booking tool, e.g. your Treatwell page')),
                ('booking_label', models.CharField(blank=True, default='Book Now', max_length=50)),
            ],
            options={
                'verbose_name': 'Services Page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
