# Generated by Django 6.0.8 on 2026-08-25 09:11

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='booking_label',
            field=models.CharField(blank=True, default='Book Now', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='booking_url',
            field=models.URLField(blank=True, default='https://www.treatwell.nl/en/place/grace-home-nails/', help_text='Link to your booking tool, e.g. your Treatwell page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Recommended: a wide photo, at least 1600px, of the salon or nail work.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_tagline',
            field=models.CharField(blank=True, default='Beautiful, carefully styled nails — from the comfort of a cosy home studio.', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
